# Generated by Django 4.0.6 on 2023-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
