# Generated by Django 4.0.6 on 2023-06-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='releaseDate',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='openingText',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.URLField(default='https://example.com'),
        ),
    ]
