# Generated by Django 4.0.6 on 2023-06-10 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_rename_image_post_image_rename_releasedate_post_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='default_image.jpg', upload_to='api/images/')),
                ('link', models.URLField(default='https://example.com')),
                ('link2', models.URLField(default='https://example.com')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
