# Generated by Django 4.0.6 on 2023-06-21 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vice_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('vice_text', models.CharField(max_length=100)),
                ('Image_Chef', models.ImageField(upload_to='api/images/')),
                ('Image_Vicechef', models.ImageField(upload_to='api/images/')),
                ('Image_Comité', models.ImageField(upload_to='api/images/')),
                ('link0', models.URLField(default='https://example.com')),
                ('link1', models.URLField(default='https://example.com')),
                ('link2', models.URLField(default='https://example.com')),
                ('link3', models.URLField(default='https://example.com')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
