# Generated by Django 4.0.6 on 2023-06-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='link0',
            field=models.URLField(default='https://facebook.com'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='link1',
            field=models.URLField(default='https://instagram.com'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='link2',
            field=models.URLField(default='https://facebook.com'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='link3',
            field=models.URLField(default='https://instagram.com'),
        ),
    ]
